#include "PluginEditor.h"
#include "PluginProcessor.h"

// Binary resource data — generated by juce_add_binary_data in CMakeLists.txt
#include <BinaryData.h>

//==============================================================================
NBS_DynaDriveAudioProcessorEditor::NBS_DynaDriveAudioProcessorEditor (
    NBS_DynaDriveAudioProcessor& p)
    : AudioProcessorEditor (&p)
    , audioProcessor (p)
    //==========================================================================
    // 1️⃣  CREATE RELAYS FIRST (no dependencies)
    //     Relay IDs MUST match the data-param attributes in v8-ui.html
    //     AND the parameter IDs in PluginProcessor.cpp's APVTS.
    //==========================================================================
    // ── Global relays ──
    , bypassRelay       (std::make_unique<juce::WebToggleButtonRelay> ("bypass"))
    , satEnableRelay    (std::make_unique<juce::WebToggleButtonRelay> ("sat_enable"))
    , compEnableRelay   (std::make_unique<juce::WebToggleButtonRelay> ("comp_enable"))

    // ── Saturation relays ──
    , driveRelay        (std::make_unique<juce::WebSliderRelay>       ("drive"))
    , evenRelay         (std::make_unique<juce::WebSliderRelay>       ("even"))
    , oddRelay          (std::make_unique<juce::WebSliderRelay>       ("odd"))
    , hCurveRelay       (std::make_unique<juce::WebSliderRelay>       ("h_curve"))

    // ── Center relays ──
    , prePostRelay      (std::make_unique<juce::WebToggleButtonRelay> ("pre_post"))
    , inputRelay        (std::make_unique<juce::WebSliderRelay>       ("input"))
    , mixRelay          (std::make_unique<juce::WebSliderRelay>       ("mix"))
    , outputRelay       (std::make_unique<juce::WebSliderRelay>       ("output"))
    , driveOutRelay     (std::make_unique<juce::WebSliderRelay>       ("drive_out"))
    , compOutRelay      (std::make_unique<juce::WebSliderRelay>       ("comp_out"))
    , satTiltFreqRelay  (std::make_unique<juce::WebSliderRelay>       ("sat_tilt_freq"))
    , satTiltSlopeRelay (std::make_unique<juce::WebSliderRelay>       ("sat_tilt_slope"))

    // ── Dynamics relays ──
    , dynamicsRelay     (std::make_unique<juce::WebSliderRelay>       ("dynamics"))
    , upRelay           (std::make_unique<juce::WebSliderRelay>       ("up"))
    , downRelay         (std::make_unique<juce::WebSliderRelay>       ("down"))

    // ── Advanced — Dynamics Detail relays ──
    , thresholdRelay    (std::make_unique<juce::WebSliderRelay>       ("threshold"))
    , ratioRelay        (std::make_unique<juce::WebSliderRelay>       ("ratio"))
    , attackTimeRelay   (std::make_unique<juce::WebSliderRelay>       ("attack_time"))
    , releaseTimeRelay  (std::make_unique<juce::WebSliderRelay>       ("release_time"))

    // ── Advanced — Post-Dyn Tilt relays ──
    , dynTiltFreqRelay  (std::make_unique<juce::WebSliderRelay>       ("dyn_tilt_freq"))
    , dynTiltSlopeRelay (std::make_unique<juce::WebSliderRelay>       ("dyn_tilt_slope"))

    // ── Advanced — M/S relays ──
    , msEnableRelay     (std::make_unique<juce::WebToggleButtonRelay> ("ms_enable"))
    , midDriveRelay     (std::make_unique<juce::WebSliderRelay>       ("mid_drive"))
    , sideDriveRelay    (std::make_unique<juce::WebSliderRelay>       ("side_drive"))

    //==========================================================================
    // 2️⃣  CREATE WEBVIEW SECOND
    //     All relays registered via .withOptionsFrom() before WebView is built.
    //     Resource provider serves index.html and JUCE frontend JS.
    //==========================================================================
    , webView (std::make_unique<juce::WebBrowserComponent> (
          juce::WebBrowserComponent::Options{}
              .withNativeIntegrationEnabled()
              .withResourceProvider ([this] (const juce::String& url) {
                  return getResource (url);
              })
              // Register every relay — order must match declaration order in .h
              .withOptionsFrom (*bypassRelay)
              .withOptionsFrom (*satEnableRelay)
              .withOptionsFrom (*compEnableRelay)
              .withOptionsFrom (*driveRelay)
              .withOptionsFrom (*evenRelay)
              .withOptionsFrom (*oddRelay)
              .withOptionsFrom (*hCurveRelay)
              .withOptionsFrom (*prePostRelay)
              .withOptionsFrom (*inputRelay)
              .withOptionsFrom (*mixRelay)
              .withOptionsFrom (*outputRelay)
              .withOptionsFrom (*driveOutRelay)
              .withOptionsFrom (*compOutRelay)
              .withOptionsFrom (*satTiltFreqRelay)
              .withOptionsFrom (*satTiltSlopeRelay)
              .withOptionsFrom (*dynamicsRelay)
              .withOptionsFrom (*upRelay)
              .withOptionsFrom (*downRelay)
              .withOptionsFrom (*thresholdRelay)
              .withOptionsFrom (*ratioRelay)
              .withOptionsFrom (*attackTimeRelay)
              .withOptionsFrom (*releaseTimeRelay)
              .withOptionsFrom (*dynTiltFreqRelay)
              .withOptionsFrom (*dynTiltSlopeRelay)
              .withOptionsFrom (*msEnableRelay)
              .withOptionsFrom (*midDriveRelay)
              .withOptionsFrom (*sideDriveRelay)
              // Native function: JS calls resizeWindow(expanded) to toggle window size
              .withNativeFunction ("resizeWindow", [this] (const juce::Array<juce::var>& args,
                                                           std::function<void (juce::var)> complete)
              {
                  bool expanded = args.size() > 0 && static_cast<bool> (args[0]);
                  isExpanded = expanded;
                  int baseH = expanded ? kExpandedHeight : kCollapsedHeight;

                  // Update aspect ratio for the new mode
                  getConstrainer()->setFixedAspectRatio (
                      static_cast<double> (kDefaultWidth) / static_cast<double> (baseH));
                  setResizeLimits (
                      static_cast<int> (kDefaultWidth * kMinScale),
                      static_cast<int> (baseH * kMinScale),
                      static_cast<int> (kDefaultWidth * kMaxScale),
                      static_cast<int> (baseH * kMaxScale));

                  // Scale current width to new height maintaining aspect ratio
                  double currentScale = static_cast<double> (getWidth()) / static_cast<double> (kDefaultWidth);
                  int newW = static_cast<int> (kDefaultWidth * currentScale);
                  int newH = static_cast<int> (baseH * currentScale);
                  setSize (newW, newH);
                  complete ({});
              })
              // Native function: JS calls requestResize(deltaX, deltaY) for drag-to-resize
              .withNativeFunction ("requestResize", [this] (const juce::Array<juce::var>& args,
                                                             std::function<void (juce::var)> complete)
              {
                  if (args.size() >= 2)
                  {
                      int dx = static_cast<int> (args[0]);
                      int dy = static_cast<int> (args[1]);
                      int newW = getWidth()  + dx;
                      int newH = getHeight() + dy;

                      // Constrainer enforces limits and aspect ratio
                      auto* c = getConstrainer();
                      if (c != nullptr)
                      {
                          juce::Rectangle<int> bounds (getX(), getY(), newW, newH);
                          c->checkBounds (bounds, getBounds(), {},
                                          false, false, true, true);
                          newW = bounds.getWidth();
                          newH = bounds.getHeight();
                      }

                      setSize (newW, newH);
                  }
                  complete ({});
              })))

    //==========================================================================
    // 3️⃣  CREATE ATTACHMENTS LAST
    //     Three-parameter constructor required by JUCE 8:
    //       (parameter, relay, undoManager)
    //     Pass nullptr for undoManager unless the plugin uses one.
    //==========================================================================
    // ── Global attachments ──
    , bypassAttachment      (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("bypass"),        *bypassRelay,       nullptr))
    , satEnableAttachment   (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("sat_enable"),   *satEnableRelay,    nullptr))
    , compEnableAttachment  (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("comp_enable"),  *compEnableRelay,   nullptr))

    // ── Saturation attachments ──
    , driveAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("drive"),          *driveRelay,        nullptr))
    , evenAttachment        (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("even"),           *evenRelay,         nullptr))
    , oddAttachment         (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("odd"),            *oddRelay,          nullptr))
    , hCurveAttachment      (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("h_curve"),        *hCurveRelay,       nullptr))

    // ── Center attachments ──
    , prePostAttachment     (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("pre_post"),       *prePostRelay,      nullptr))
    , inputAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("input"),          *inputRelay,        nullptr))
    , mixAttachment         (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("mix"),            *mixRelay,          nullptr))
    , outputAttachment      (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("output"),         *outputRelay,       nullptr))
    , driveOutAttachment    (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("drive_out"),      *driveOutRelay,     nullptr))
    , compOutAttachment     (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("comp_out"),       *compOutRelay,      nullptr))
    , satTiltFreqAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("sat_tilt_freq"),  *satTiltFreqRelay,  nullptr))
    , satTiltSlopeAttachment(std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("sat_tilt_slope"), *satTiltSlopeRelay, nullptr))

    // ── Dynamics attachments ──
    , dynamicsAttachment    (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dynamics"),       *dynamicsRelay,     nullptr))
    , upAttachment          (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("up"),             *upRelay,           nullptr))
    , downAttachment        (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("down"),           *downRelay,         nullptr))

    // ── Advanced — Dynamics Detail attachments ──
    , thresholdAttachment   (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("threshold"),      *thresholdRelay,    nullptr))
    , ratioAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("ratio"),          *ratioRelay,        nullptr))
    , attackTimeAttachment  (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("attack_time"),    *attackTimeRelay,   nullptr))
    , releaseTimeAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("release_time"),   *releaseTimeRelay,  nullptr))

    // ── Advanced — Post-Dyn Tilt attachments ──
    , dynTiltFreqAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dyn_tilt_freq"),  *dynTiltFreqRelay,  nullptr))
    , dynTiltSlopeAttachment(std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dyn_tilt_slope"), *dynTiltSlopeRelay, nullptr))

    // ── Advanced — M/S attachments ──
    , msEnableAttachment    (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("ms_enable"),      *msEnableRelay,     nullptr))
    , midDriveAttachment    (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("mid_drive"),      *midDriveRelay,     nullptr))
    , sideDriveAttachment   (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("side_drive"),     *sideDriveRelay,    nullptr))
{
    addAndMakeVisible (*webView);
    webView->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Default size: collapsed (740x418). Advanced panel expands to 740x548.
    setSize (kDefaultWidth, kCollapsedHeight);
    // useBottomRightCornerResizer = false: native WebView always covers JUCE
    // components, so the corner resizer would be invisible. Hosts and OS window
    // frames provide their own resize handles.
    setResizable (true, false);
    setResizeLimits (
        static_cast<int> (kDefaultWidth  * kMinScale),
        static_cast<int> (kCollapsedHeight * kMinScale),
        static_cast<int> (kDefaultWidth  * kMaxScale),
        static_cast<int> (kExpandedHeight * kMaxScale));
    getConstrainer()->setFixedAspectRatio (
        static_cast<double> (kDefaultWidth) / static_cast<double> (isExpanded ? kExpandedHeight : kCollapsedHeight));

    // Start meter update timer at ~30 Hz
    startTimerHz (30);
}

NBS_DynaDriveAudioProcessorEditor::~NBS_DynaDriveAudioProcessorEditor()
{
    stopTimer();
    // Members destroyed in reverse declaration order automatically:
    //   Attachments → webView → Relays (correct order, safe)
}

//==============================================================================
void NBS_DynaDriveAudioProcessorEditor::timerCallback()
{
    // Read peak levels from processor (atomic, lock-free) and reset for next cycle
    float inL  = audioProcessor.meterInL.exchange  (0.0f, std::memory_order_relaxed);
    float inR  = audioProcessor.meterInR.exchange  (0.0f, std::memory_order_relaxed);
    float outL = audioProcessor.meterOutL.exchange (0.0f, std::memory_order_relaxed);
    float outR = audioProcessor.meterOutR.exchange (0.0f, std::memory_order_relaxed);

    // Convert linear amplitude (0.0–1.0+) to percentage (0–100) for JS meter bars
    auto toPct = [] (float linear) {
        return std::clamp (linear * 100.0f, 0.0f, 100.0f);
    };

    // Read gain reduction (dB, negative = compression, 0 = none)
    float gr = audioProcessor.meterGR.load (std::memory_order_relaxed);

    auto meterData = std::make_unique<juce::DynamicObject>();
    meterData->setProperty ("inL",  toPct (inL));
    meterData->setProperty ("inR",  toPct (inR));
    meterData->setProperty ("outL", toPct (outL));
    meterData->setProperty ("outR", toPct (outR));
    meterData->setProperty ("gr",   gr);

    webView->emitEventIfBrowserIsVisible ("meter_update", juce::var (meterData.release()));
}

//==============================================================================
void NBS_DynaDriveAudioProcessorEditor::paint (juce::Graphics& g)
{
    // WebView fills the entire editor; no painting needed.
    g.fillAll (juce::Colour (0xff141414));
}

void NBS_DynaDriveAudioProcessorEditor::resized()
{
    webView->setBounds (getLocalBounds());

    // Inject CSS zoom to scale the fixed-layout WebView content proportionally
    const double scale = static_cast<double> (getWidth()) / static_cast<double> (kDefaultWidth);
    juce::String js = "document.body.style.zoom = '" + juce::String (scale, 4) + "';";
    webView->evaluateJavascript (js, nullptr);
}

//==============================================================================
// WebView Resource Provider — explicit URL mapping (JUCE 8 pattern)
//
// BinaryData converts file paths to C++ identifiers:
//   Source/ui/public/index.html           → BinaryData::index_html
//   Source/ui/public/js/juce/index.js     → BinaryData::index_js
//   Source/ui/public/js/juce/check_native_interop.js
//                                         → BinaryData::check_native_interop_js
//
// HTML requests use original paths, so we map them explicitly.
//==============================================================================
std::optional<juce::WebBrowserComponent::Resource>
NBS_DynaDriveAudioProcessorEditor::getResource (const juce::String& url)
{
    auto makeVector = [] (const char* data, int size)
    {
        return std::vector<std::byte> (
            reinterpret_cast<const std::byte*> (data),
            reinterpret_cast<const std::byte*> (data) + size);
    };

    // Main HTML page
    if (url == "/" || url == "/index.html")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_html, BinaryData::index_htmlSize),
            juce::String ("text/html")
        };
    }

    // JUCE WebView frontend library
    if (url == "/js/juce/index.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_js, BinaryData::index_jsSize),
            juce::String ("application/javascript")
        };
    }

    // JUCE native interop verification script (REQUIRED — prevents silent bridge failure)
    if (url == "/js/juce/check_native_interop.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::check_native_interop_js,
                        BinaryData::check_native_interop_jsSize),
            juce::String ("application/javascript")
        };
    }

    // 404 — unhandled resource
    return std::nullopt;
}
