#include "PluginEditor.h"
#include "PluginProcessor.h"

// Binary resource data — generated by juce_add_binary_data in CMakeLists.txt
#include <BinaryData.h>

//==============================================================================
NBS_DynaDriveAudioProcessorEditor::NBS_DynaDriveAudioProcessorEditor (
    NBS_DynaDriveAudioProcessor& p)
    : AudioProcessorEditor (&p)
    , audioProcessor (p)
    //==========================================================================
    // 1️⃣  CREATE RELAYS FIRST (no dependencies)
    //     Relay IDs MUST match the data-param attributes in v8-ui.html
    //     AND the parameter IDs in PluginProcessor.cpp's APVTS.
    //==========================================================================
    // ── Saturation relays ──
    , driveRelay        (std::make_unique<juce::WebSliderRelay>       ("drive"))
    , evenRelay         (std::make_unique<juce::WebSliderRelay>       ("even"))
    , oddRelay          (std::make_unique<juce::WebSliderRelay>       ("odd"))
    , hCurveRelay       (std::make_unique<juce::WebSliderRelay>       ("h_curve"))

    // ── Center relays ──
    , prePostRelay      (std::make_unique<juce::WebToggleButtonRelay> ("pre_post"))
    , inputRelay        (std::make_unique<juce::WebSliderRelay>       ("input"))
    , mixRelay          (std::make_unique<juce::WebSliderRelay>       ("mix"))
    , outputRelay       (std::make_unique<juce::WebSliderRelay>       ("output"))
    , satTiltFreqRelay  (std::make_unique<juce::WebSliderRelay>       ("sat_tilt_freq"))
    , satTiltSlopeRelay (std::make_unique<juce::WebSliderRelay>       ("sat_tilt_slope"))

    // ── Dynamics relays ──
    , dynamicsRelay     (std::make_unique<juce::WebSliderRelay>       ("dynamics"))
    , upRelay           (std::make_unique<juce::WebSliderRelay>       ("up"))
    , downRelay         (std::make_unique<juce::WebSliderRelay>       ("down"))

    // ── Advanced — Dynamics Detail relays ──
    , thresholdRelay    (std::make_unique<juce::WebSliderRelay>       ("threshold"))
    , ratioRelay        (std::make_unique<juce::WebSliderRelay>       ("ratio"))
    , attackTimeRelay   (std::make_unique<juce::WebSliderRelay>       ("attack_time"))
    , releaseTimeRelay  (std::make_unique<juce::WebSliderRelay>       ("release_time"))

    // ── Advanced — Post-Dyn Tilt relays ──
    , dynTiltFreqRelay  (std::make_unique<juce::WebSliderRelay>       ("dyn_tilt_freq"))
    , dynTiltSlopeRelay (std::make_unique<juce::WebSliderRelay>       ("dyn_tilt_slope"))

    // ── Advanced — M/S relays ──
    , msEnableRelay     (std::make_unique<juce::WebToggleButtonRelay> ("ms_enable"))
    , midDriveRelay     (std::make_unique<juce::WebSliderRelay>       ("mid_drive"))
    , sideDriveRelay    (std::make_unique<juce::WebSliderRelay>       ("side_drive"))

    //==========================================================================
    // 2️⃣  CREATE WEBVIEW SECOND
    //     All relays registered via .withOptionsFrom() before WebView is built.
    //     Resource provider serves index.html and JUCE frontend JS.
    //==========================================================================
    , webView (std::make_unique<juce::WebBrowserComponent> (
          juce::WebBrowserComponent::Options{}
              .withNativeIntegrationEnabled()
              .withResourceProvider ([this] (const juce::String& url) {
                  return getResource (url);
              })
              // Register every relay — order must match declaration order in .h
              .withOptionsFrom (*driveRelay)
              .withOptionsFrom (*evenRelay)
              .withOptionsFrom (*oddRelay)
              .withOptionsFrom (*hCurveRelay)
              .withOptionsFrom (*prePostRelay)
              .withOptionsFrom (*inputRelay)
              .withOptionsFrom (*mixRelay)
              .withOptionsFrom (*outputRelay)
              .withOptionsFrom (*satTiltFreqRelay)
              .withOptionsFrom (*satTiltSlopeRelay)
              .withOptionsFrom (*dynamicsRelay)
              .withOptionsFrom (*upRelay)
              .withOptionsFrom (*downRelay)
              .withOptionsFrom (*thresholdRelay)
              .withOptionsFrom (*ratioRelay)
              .withOptionsFrom (*attackTimeRelay)
              .withOptionsFrom (*releaseTimeRelay)
              .withOptionsFrom (*dynTiltFreqRelay)
              .withOptionsFrom (*dynTiltSlopeRelay)
              .withOptionsFrom (*msEnableRelay)
              .withOptionsFrom (*midDriveRelay)
              .withOptionsFrom (*sideDriveRelay)))

    //==========================================================================
    // 3️⃣  CREATE ATTACHMENTS LAST
    //     Three-parameter constructor required by JUCE 8:
    //       (parameter, relay, undoManager)
    //     Pass nullptr for undoManager unless the plugin uses one.
    //==========================================================================
    // ── Saturation attachments ──
    , driveAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("drive"),          *driveRelay,        nullptr))
    , evenAttachment        (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("even"),           *evenRelay,         nullptr))
    , oddAttachment         (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("odd"),            *oddRelay,          nullptr))
    , hCurveAttachment      (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("h_curve"),        *hCurveRelay,       nullptr))

    // ── Center attachments ──
    , prePostAttachment     (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("pre_post"),       *prePostRelay,      nullptr))
    , inputAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("input"),          *inputRelay,        nullptr))
    , mixAttachment         (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("mix"),            *mixRelay,          nullptr))
    , outputAttachment      (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("output"),         *outputRelay,       nullptr))
    , satTiltFreqAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("sat_tilt_freq"),  *satTiltFreqRelay,  nullptr))
    , satTiltSlopeAttachment(std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("sat_tilt_slope"), *satTiltSlopeRelay, nullptr))

    // ── Dynamics attachments ──
    , dynamicsAttachment    (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dynamics"),       *dynamicsRelay,     nullptr))
    , upAttachment          (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("up"),             *upRelay,           nullptr))
    , downAttachment        (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("down"),           *downRelay,         nullptr))

    // ── Advanced — Dynamics Detail attachments ──
    , thresholdAttachment   (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("threshold"),      *thresholdRelay,    nullptr))
    , ratioAttachment       (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("ratio"),          *ratioRelay,        nullptr))
    , attackTimeAttachment  (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("attack_time"),    *attackTimeRelay,   nullptr))
    , releaseTimeAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("release_time"),   *releaseTimeRelay,  nullptr))

    // ── Advanced — Post-Dyn Tilt attachments ──
    , dynTiltFreqAttachment (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dyn_tilt_freq"),  *dynTiltFreqRelay,  nullptr))
    , dynTiltSlopeAttachment(std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("dyn_tilt_slope"), *dynTiltSlopeRelay, nullptr))

    // ── Advanced — M/S attachments ──
    , msEnableAttachment    (std::make_unique<juce::WebToggleButtonParameterAttachment> (*audioProcessor.parameters.getParameter ("ms_enable"),      *msEnableRelay,     nullptr))
    , midDriveAttachment    (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("mid_drive"),      *midDriveRelay,     nullptr))
    , sideDriveAttachment   (std::make_unique<juce::WebSliderParameterAttachment>       (*audioProcessor.parameters.getParameter ("side_drive"),     *sideDriveRelay,    nullptr))
{
    addAndMakeVisible (*webView);
    webView->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Default size: collapsed (740x400). Advanced panel expands to 740x548.
    setSize (kCollapsedWidth, kCollapsedHeight);
    setResizable (false, false);
}

NBS_DynaDriveAudioProcessorEditor::~NBS_DynaDriveAudioProcessorEditor()
{
    // Members destroyed in reverse declaration order automatically:
    //   Attachments → webView → Relays (correct order, safe)
}

//==============================================================================
void NBS_DynaDriveAudioProcessorEditor::paint (juce::Graphics& g)
{
    // WebView fills the entire editor; no painting needed.
    g.fillAll (juce::Colour (0xff141414));
}

void NBS_DynaDriveAudioProcessorEditor::resized()
{
    webView->setBounds (getLocalBounds());
}

//==============================================================================
// WebView Resource Provider — explicit URL mapping (JUCE 8 pattern)
//
// BinaryData converts file paths to C++ identifiers:
//   Source/ui/public/index.html           → BinaryData::index_html
//   Source/ui/public/js/juce/index.js     → BinaryData::index_js
//   Source/ui/public/js/juce/check_native_interop.js
//                                         → BinaryData::check_native_interop_js
//
// HTML requests use original paths, so we map them explicitly.
//==============================================================================
std::optional<juce::WebBrowserComponent::Resource>
NBS_DynaDriveAudioProcessorEditor::getResource (const juce::String& url)
{
    auto makeVector = [] (const char* data, int size)
    {
        return std::vector<std::byte> (
            reinterpret_cast<const std::byte*> (data),
            reinterpret_cast<const std::byte*> (data) + size);
    };

    // Main HTML page
    if (url == "/" || url == "/index.html")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_html, BinaryData::index_htmlSize),
            juce::String ("text/html")
        };
    }

    // JUCE WebView frontend library
    if (url == "/js/juce/index.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_js, BinaryData::index_jsSize),
            juce::String ("application/javascript")
        };
    }

    // JUCE native interop verification script (REQUIRED — prevents silent bridge failure)
    if (url == "/js/juce/check_native_interop.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::check_native_interop_js,
                        BinaryData::check_native_interop_jsSize),
            juce::String ("application/javascript")
        };
    }

    // 404 — unhandled resource
    return std::nullopt;
}
